#!/usr/bin/env python3
"""
Config merge script for blah2 and tar1090-node

Designed to be run in both blah2 and blah2-api containers with baked-in configs.
Merges default.yml + user.yml + forced.yml into config.yml.
Also syncs the node_id field in user.yml from Mender device identity (/data/mender/node_id).
Generates tar1090.env for tar1090-node if the tar1090 section exists in config.
Generates retina-tracker.yaml for the retina-tracker sidecar if the
retina_tracker section exists in config.

Takes as inputs:
1. Defaults directory - holds baked-in default.yml and forced.yml
2. User config path - the path to the shared persistent directory (in the /data partition)
   where the user config overlay, user.yml. If this does not exist, it is created by copying defaults.yml.
3. Output config path - the output location of the generated merged config file,
   should live separately in each container to avoid race conditions

Merge order (later overrides earlier):
  default.yml -> user.yml -> forced.yml

Outputs:
  - config.yml: Merged configuration for blah2
  - tar1090.env: Environment variables for tar1090-node
  - retina-tracker.yaml: Config overrides for the retina-tracker sidecar
"""

import os
import shutil
import sys

import yaml
from mergedeep import merge


def get_node_id_from_mender():
    """Read node_id from Mender device identity file (generated by mender-device-identity)"""
    node_id_file = '/data/mender/node_id'
    try:
        with open(node_id_file) as f:
            node_id = f.read().strip()
            if node_id:
                return node_id
    except FileNotFoundError:
        print(f"Mender node_id file not found: {node_id_file}")
    except Exception as e:
        print(f"Could not read node_id from {node_id_file}: {e}")

    return None


def generate_env_file(config, output_dir):
    """Generate .env file for ADS-B services (readsb, tar1090) from merged config"""
    if 'tar1090' not in config:
        print("No tar1090 config found, skipping .env generation")
        return

    tar1090_config = config['tar1090']
    # Use tar1090.location if set, otherwise fall back to location.rx (receiver location)
    location = tar1090_config.get('location') or (config.get('location') or {}).get('rx') or {}

    env_path = os.path.join(output_dir, 'tar1090.env')
    print(f"Writing tar1090 .env to {env_path}")

    # Write to temp file first, then atomic rename
    temp_path = env_path + '.tmp.' + str(os.getpid())
    lat = location.get('latitude')
    lon = location.get('longitude')
    alt = location.get('altitude')
    sited = lat is not None and lon is not None

    with open(temp_path, 'w') as f:
        f.write("# Auto-generated by config-merger - do not edit manually\n\n")

        # Receiver location (matches tar1090-node .env.example format).
        # Omitted when unset. This used to default to 0, which is Null Island:
        # a real place the node then claimed to be.
        f.write("# Receiver location\n")
        if sited:
            f.write(f"RECEIVER_LAT={lat}\n")
            f.write(f"RECEIVER_LON={lon}\n")
            f.write(f"RECEIVER_ALT={alt if alt is not None else 0}\n\n")
        else:
            f.write("# unset: no receiver location has been configured\n\n")

        # adsb.lol integration. Forced off without a location whatever the
        # config says: the query is a radius around the receiver, so with no
        # receiver there is no query to make, only a wrong one.
        adsblol = bool(tar1090_config.get('adsblol_fallback', False)) and sited
        f.write("# adsb.lol integration\n")
        f.write(f"ADSBLOL_ENABLED={'true' if adsblol else 'false'}\n")
        f.write(f"ADSBLOL_RADIUS={tar1090_config.get('adsblol_radius', 40)}\n\n")

        # External ADS-B feed for readsb
        adsb_source = tar1090_config.get('adsb_source', '')
        if adsb_source:
            f.write("# readsb external feed\n")
            f.write(f"READSB_NET_CONNECTOR={adsb_source}\n")

    os.rename(temp_path, env_path)
    print("tar1090 .env generated successfully!")

    # Copy .env to Mender compose directories for variable substitution
    # mender-docker-compose uses current/ (active) and new/ (staging during update)
    for slot in ['current', 'new']:
        manifests_dir = f'/data/mender-docker-compose/{slot}/manifests'
        env_dest = os.path.join(manifests_dir, '.env')
        try:
            if os.path.isdir(manifests_dir):
                shutil.copy(env_path, env_dest)
                print(f"Copied .env to {env_dest}")
        except Exception as e:
            print(f"Note: Could not copy to {env_dest}: {e}")


def generate_retina_tracker_config(config, output_dir):
    """Generate a config file for the retina-tracker sidecar from the merged
    config's `retina_tracker` section.

    retina_tracker.config.load_config() shallow-merges this per top-level
    section (`default_config[key].update(loaded[key])`), so only the
    overridden keys need to be present here - everything else falls back to
    the package's own built-in defaults. All fields under `retina_tracker`
    here are assumed to belong to retina-tracker's own `tracker` section;
    revisit this mapping if fields for its other sections (`process_noise`,
    `tracklet`, `adsb`, ...) are ever added to default.yml.
    """
    if 'retina_tracker' not in config:
        print("No retina_tracker config found, skipping retina-tracker.yaml generation")
        return

    output_path = os.path.join(output_dir, 'retina-tracker.yaml')
    print(f"Writing retina-tracker config to {output_path}")

    # Write to temp file first, then atomic rename
    temp_path = output_path + '.tmp.' + str(os.getpid())
    with open(temp_path, 'w') as f:
        yaml.dump({'tracker': config['retina_tracker']}, f, default_flow_style=False, sort_keys=False)
    os.rename(temp_path, output_path)
    print("retina-tracker.yaml generated successfully!")


def migrate_gain_reduction(config):
    """Convert legacy scalar gainReduction (pre-per-tuner) to [reference, surveillance] pair.

    Older user.yml overlays persisted on devices may still carry a single scalar value
    for capture.device.gainReduction, which would otherwise clobber the new default.yml's
    list value during merge and break blah2's per-tuner RSPduo gain support.
    """
    try:
        gain = config['capture']['device']['gainReduction']
    except (KeyError, TypeError):
        return

    if isinstance(gain, (int, float)):
        print(f"Migrating legacy scalar gainReduction ({gain}) to per-tuner pair [{gain}, {gain}]")
        config['capture']['device']['gainReduction'] = [gain, gain]


def ensure_node_id(user_config_path):
    """Add/update node_id in user config from Mender device identity"""
    try:
        # Load current user config
        with open(user_config_path) as f:
            user_config = yaml.safe_load(f) or {}

        # Read node_id from Mender device identity (generated by mender-device-identity script)
        node_id = get_node_id_from_mender()
        if not node_id:
            print("No Mender node_id found, skipping node_id sync")
            return

        # Check if node_id already exists
        if 'network' in user_config and 'node_id' in user_config['network']:
            current_id = user_config['network']['node_id']
            if current_id == node_id:
                print(f"Node ID already correct: {node_id}")
                return
            else:
                # Node ID changed (board swap) - update it
                print(f"Node ID mismatch - updating from '{current_id}' to '{node_id}'")
        else:
            print(f"Syncing node_id from Mender identity: {node_id}")

        # Add/update node_id to network section
        if 'network' not in user_config:
            user_config['network'] = {}
        user_config['network']['node_id'] = node_id

        # Write back to user config (atomic)
        temp_path = user_config_path + '.node_id_tmp.' + str(os.getpid())
        with open(temp_path, 'w') as f:
            yaml.dump(user_config, f, default_flow_style=False, sort_keys=False)
        os.rename(temp_path, user_config_path)

        print(f"Node ID set in {user_config_path}")

    except Exception as e:
        print(f"Warning: Failed to ensure node_id: {e}")
        # Don't exit - continue with merge even if node_id fails


def main():
    # Parse command-line arguments
    if len(sys.argv) != 4:
        print("Usage: merge_config.py <defaults_dir> <user_config_path> <output_config_path>")
        print("Example: merge_config.py /config/defaults /data/retina-node/config/user.yml /data/retina-node/config/config.yml")
        sys.exit(1)

    defaults_dir = sys.argv[1]
    user_config_path = sys.argv[2]
    output_config_path = sys.argv[3]

    # Construct paths
    default_config = os.path.join(defaults_dir, 'default.yml')
    forced_config = os.path.join(defaults_dir, 'forced.yml')

    try:
        # Load default config (baked into container)
        print(f"Loading default config from {default_config}")
        with open(default_config) as f:
            config = yaml.safe_load(f)

        if not config:
            print("ERROR: Default config is empty or invalid")
            sys.exit(1)

        # Create user config from defaults if it doesn't exist (atomic)
        if not os.path.exists(user_config_path):
            print("User config not found, copying from defaults...")
            os.makedirs(os.path.dirname(user_config_path), exist_ok=True)

            # Write to temp file first, then atomic rename
            temp_path = user_config_path + '.tmp.' + str(os.getpid())
            shutil.copy(default_config, temp_path)
            try:
                os.rename(temp_path, user_config_path)  # Atomic on POSIX
                print(f"Created {user_config_path}")
            except (FileExistsError, OSError):
                # Another process created it first, clean up temp
                if os.path.exists(temp_path):
                    os.remove(temp_path)
                print("User config was created by another process")

        # Ensure node_id exists and matches hardware (add/update if needed, Pi only)
        ensure_node_id(user_config_path)

        # Overlay user config if it exists and has content
        if os.path.exists(user_config_path):
            print(f"Loading user config from {user_config_path}")
            with open(user_config_path) as f:
                user = yaml.safe_load(f)

            if user:  # Only merge if user.yml has actual content
                print("Applying user overrides...")
                merge(config, user)
            else:
                print("User config is empty, using defaults")

        # Overlay forced config (highest priority)
        if os.path.exists(forced_config):
            print(f"Loading forced config from {forced_config}")
            with open(forced_config) as f:
                forced = yaml.safe_load(f)

            if forced:  # Only merge if content exists
                print("Applying forced overrides...")
                merge(config, forced)

        # Migrate legacy field formats forward (e.g. scalar -> per-tuner gainReduction)
        migrate_gain_reduction(config)

        # Write merged config to output
        print(f"Writing merged config to {output_config_path}")
        os.makedirs(os.path.dirname(output_config_path), exist_ok=True)
        with open(output_config_path, 'w') as f:
            yaml.dump(config, f, default_flow_style=False, sort_keys=False)

        # Generate .env file for tar1090-node
        generate_env_file(config, os.path.dirname(output_config_path))

        # Generate config file for the retina-tracker sidecar
        generate_retina_tracker_config(config, os.path.dirname(output_config_path))

        print("Config merge completed successfully!")

    except Exception as e:
        print(f"ERROR during config merge: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()
